# Generated by Django 3.2.5 on 2022-08-11 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dob',
            field=models.DateField(help_text='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='fname',
            field=models.CharField(help_text='First Name', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='lname',
            field=models.CharField(help_text='Last Name', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='married',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=10),
        ),
    ]
