# Generated by Django 3.1.5 on 2022-05-17 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='summary',
            field=models.TextField(default='This is cool!'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='This is cool!'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.TextField(default=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.TextField(default='Shirt'),
        ),
    ]
