# Generated by Django 3.2.5 on 2022-07-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='post_image'),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='category',
            field=models.CharField(default=1, max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
