# Generated by Django 3.1.5 on 2022-06-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='1.jpg', upload_to='profile_pics'),
        ),
    ]
