# Generated by Django 3.1.5 on 2022-06-10 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20220610_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.category'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='series',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.series'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tslug',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
