# Generated by Django 3.1.5 on 2022-06-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20220610_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='series',
            field=models.CharField(max_length=100),
        ),
    ]
