# Generated by Django 3.1.5 on 2022-06-10 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20220610_1803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='summary',
            new_name='category_summary',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='summary',
            new_name='series_summary',
        ),
    ]
