# Generated by Django 3.1.5 on 2022-06-10 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20220610_1806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='slug',
            new_name='category_slug',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='category',
            new_name='series_category',
        ),
        migrations.RenameField(
            model_name='tutorial',
            old_name='series',
            new_name='tseries',
        ),
        migrations.RenameField(
            model_name='tutorial',
            old_name='slug',
            new_name='tslug',
        ),
    ]
