# Generated by Django 3.1.5 on 2022-06-11 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20220610_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='series_category',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='tseries',
        ),
    ]
