# Generated by Django 3.2.5 on 2023-02-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20230209_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myclubmember',
            name='lname',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='venue',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
