# Generated by Django 3.1.5 on 2022-05-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('slug', models.SlugField()),
                ('author', models.CharField(max_length=25)),
                ('time_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
